import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results';
import requests from '../utils/requests'

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>PWA Hulu 2.0 | Light Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <Header />

      <Nav />

      <Results results={results}/>

    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTopRated.url
  }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    }
  }
} 